# -*- coding: utf-8 -*-
"""
Created on 2026/03/04 22:52:40
@author: Whenxuan Wang
@email: wwhenxuan@gmail.com
@url: https://github.com/wwhenxuan/S2Generator
"""

import numpy as np

from s2generator.utils._tools import (
    linear_interpolation,
    cubic_spline_interpolation,
    lagrange_interpolation,
)


def amplitude_modulation(
    time_series: np.ndarray,
    num_changepoints: int = 5,
    mean_amplitude: float = 1.0,
    amplitude_variation: float = 1.0,
    interpolation_method: str = "linear",
) -> np.ndarray:
    """
    Perform amplitude modulation on the input time series.
    This augmentation introduces scale trends and change points into the time series
    by multiplying the signal with a piecewise linear trend.
    The modulation trend is generated by sampling change points and interpolating amplitudes between them.

    :param time_series: Input time series, a 1D numpy array
    :param num_changepoints: Number of change points to introduce in the modulation trend.
    :param mean_amplitude: The mean amplitude of the modulation trend.
    :param amplitude_variation: The variation of the amplitude around the mean.
    :param interpolation_method: The method to interpolate the modulation trend.
                                 Options are "linear", "cubic", or "lagrange".

    :return: Amplitude modulated time series, a 1D numpy array of the same length as the input series.
    """
