# -*- coding: utf-8 -*-
"""
This module primarily houses tools and auxiliary functions or classes,
including functions for converting string notation into Markdown syntax,
normalizing time series data,
obtaining the current time,
saving and loading S2 data,
and calculating and measuring the similarity between two time series datasets.

Created on 2025/08/3 00:01:56
@author: Whenxuan Wang
@email: wwhenxuan@gmail.com
"""

__all__ = [
    "symbol_to_markdown",
    "z_score_normalization",
    "max_min_normalization",
    "get_time_now",
    "save_s2data",
    "load_s2data",
    "eacf_rlike",
    "yule_walker",
    "linear_interpolation",
    "cubic_spline_interpolation",
    "lagrange_interpolation",
    "fft",
    "fftshift",
    "ifft",
    "ifftshift",
    "wasserstein_distance",
    "wasserstein_distance_matrix",
    "plot_wasserstein_heatmap",
    "PrintStatus",
    "STL",
    "STLResult",
    "simple_moving_average",
    "weighted_moving_average",
    "gaussian_smoothing",
    "savgol_smoothing",
    "exponential_smoothing",
    "smooth_show_info",
    "MovingDecomp",
    "plot_univariate_time_series",
    "plot_symbol_series",
    "plot_adjacency_matrix",
    "plot_graph",
    "plot_multivariate_time_series",
    "plot_correlation",
    "plot_iq_series",
    "plot_iq_analysis",
    "multivariate_correlation",
    "plot_symbol",
    "plot_shapiro_wilk",
    "plot_simulator_statistics",
    "generate_arma_samples",
    "generate_nonstationary_sine",
    "generate_variable_frequency_sine",
    "generate_sine_with_local_frequency_changes",
    "generate_triangle_wave",
    "generate_square_wave",
    "generate_sawtooth_wave",
    "generate_damped_oscillation",
    "generate_chirp_signal",
    "generate_impulse_signal",
    "generate_step_signal",
    "generate_ramp_signal",
    "generate_exponential_signal",
    "generate_logarithmic_signal",
    "generate_stock_price",
    "generate_electrocardiogram",
    "generate_electroencephalogram",
    "AVAILABLE_UNIVARIATE_DATASETS",
    "AVAILABLE_MULTIVARIATE_DATASETS",
    "AVAILABLE_DEEPMIMO_DATASETS",
    "AVAILABLE_SYNTHETIC_GENERATORS",
    "list_datasets",
    "list_deepmimo_speeds",
    "load_univariate",
    "load_multivariate",
    "load_deepmimo_iq",
    "generate",
    "save_table",
    "discrete_entropy",
    "spectral_entropy",
    "omega",
    "mvspectrum",
    "normalize_mvspectrum",
    "spectrum_of_linear_combination",
    "univariate_spectrum",
    "sqrt_matrix",
    "whiten",
    "WhitenResult",
    "SlowFeatureAnalysis",
    "ForeCA",
    "initialize_weightvector",
    "plot_omega",
    "plot_spectrum",
    "plot_foreca",
    "plot_sfa",
]

from s2generator.symbol.print_symbol import symbol_to_markdown

from .tools import (
    cubic_spline_interpolation,
    eacf_rlike,
    fft,
    fftshift,
    get_time_now,
    ifft,
    ifftshift,
    lagrange_interpolation,
    linear_interpolation,
    load_s2data,
    max_min_normalization,
    save_s2data,
    save_table,
    yule_walker,
    z_score_normalization,
)

from .distance import (
    plot_wasserstein_heatmap,
    wasserstein_distance,
    wasserstein_distance_matrix,
)

from .smooth import (
    exponential_smoothing,
    gaussian_smoothing,
    savgol_smoothing,
    simple_moving_average,
    smooth_show_info,
    weighted_moving_average,
)

from .decomposition import MovingDecomp, STL, STLResult

from .correlation import multivariate_correlation

from .visualization import (
    plot_univariate_time_series,
    plot_symbol_series,
    plot_adjacency_matrix,
    plot_graph,
    plot_multivariate_time_series,
    plot_correlation,
    plot_iq_series,
    plot_iq_analysis,
    plot_symbol,
    plot_shapiro_wilk,
    plot_simulator_statistics,
    plot_omega,
    plot_spectrum,
    plot_foreca,
    plot_sfa,
)

from .data import (
    AVAILABLE_DEEPMIMO_DATASETS,
    AVAILABLE_MULTIVARIATE_DATASETS,
    AVAILABLE_UNIVARIATE_DATASETS,
    AVAILABLE_SYNTHETIC_GENERATORS,
    PrintStatus,
    list_datasets,
    list_deepmimo_speeds,
    load_deepmimo_iq,
    load_multivariate,
    load_univariate,
    generate,
    generate_arma_samples,
    generate_nonstationary_sine,
    generate_variable_frequency_sine,
    generate_sine_with_local_frequency_changes,
    generate_triangle_wave,
    generate_square_wave,
    generate_sawtooth_wave,
    generate_damped_oscillation,
    generate_chirp_signal,
    generate_impulse_signal,
    generate_step_signal,
    generate_ramp_signal,
    generate_exponential_signal,
    generate_logarithmic_signal,
    generate_stock_price,
    generate_electrocardiogram,
    generate_electroencephalogram,
)

from .forecastability import (
    ForeCA,
    SlowFeatureAnalysis,
    WhitenResult,
    discrete_entropy,
    initialize_weightvector,
    mvspectrum,
    normalize_mvspectrum,
    omega,
    spectral_entropy,
    spectrum_of_linear_combination,
    univariate_spectrum,
    sqrt_matrix,
    whiten,
)
