# -*- coding: utf-8 -*-
"""
This file primarily contains utility functions,
such as those for obtaining the current time,
ensuring the existence of a specified directory,
saving and loading S2 data,
and performing two different normalization operations.

Created on 2025/08/23 17:09:18
@author: Whenxuan Wang
@email: wwhenxuan@gmail.com
@url: https://github.com/wwhenxuan/S2Generator
"""
__all__ = [
    "get_time_now",
    "ensure_directory_exists",
    "save_s2data",
    "save_npy",
    "save_npz",
    "load_s2data",
    "load_npz",
    "load_npy",
    "is_all_zeros",
    "z_score_normalization",
    "max_min_normalization",
    "fft",
    "ifft",
    "fftshift",
    "ifftshift",
    "generate_arma_samples",
    "generate_nonstationary_sine",
    "eacf_rlike",
    "yule_walker",
]

import os
from os import path
from datetime import datetime
import numpy as np
from numpy import bool_
from numpy import fft as np_fft

import pandas as pd

from typing import Optional, Dict, Union, Tuple

from s2generator import Node, NodeList


def get_time_now():
    """Get current time to string"""
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def ensure_directory_exists(file_path: str) -> str:
    """
    Ensures the directory in the given file path exists, creating it if necessary.

    This function handles both file paths and directory paths:
    - For file paths (ending with .npy, .npz, or .json), ensures the parent directory exists
    - For directory paths, ensures the directory itself exists

    :param file_path: Complete path including filename or directory path
    :return: Full path to the file that should be used for saving
    """
    # Determine if path ends with a file extension
    if (
        file_path.endswith(".npy")
        or file_path.endswith(".npz")
        or file_path.endswith(".json")
    ):
        # Extract directory from file path
        directory = os.path.dirname(file_path)
        return_path = file_path
    else:
        # Treat as directory path
        directory = file_path
        return_path = os.path.join(file_path, "s2data.npz")

    # Create directory if it doesn't exist
    if directory and not path.exists(directory):
        os.makedirs(directory)

    return return_path


def save_s2data(
    symbol: Union[str, "Node", "NodeList"],
    excitation: Union[int, bool, float, np.ndarray],
    response: Union[int, bool, float, np.ndarray],
    save_path: str = None,
) -> bool:
    """
    Saves S2 data (symbolic expressions and time series) to the specified location.

    This function works with load_s2data to provide a complete save/load workflow.
    Supports multiple file formats (.npy, .npz) and handles directory creation.

    :param symbol: Symbolic expression data generated by S2Generator (Node, NodeList, or str)
    :param excitation: Input excitation time series data
    :param response: Response time series data obtained from the system
    :param save_path: Save location with two input options:
                     - Directory path: data will be saved as 's2data.npz' in this directory
                     - Full file path: must end with .npy or .npz extension
    :return: Boolean indicating success status of the save operation.
    """
    # Ensure directory exists and get final save path
    save_path = ensure_directory_exists(file_path=save_path)

    # Save based on file extension
    if save_path.endswith(".npy"):
        status = save_npy(
            data={
                "symbol": str(symbol),
                "excitation": excitation,
                "response": response,
            },
            save_path=save_path,
        )
    elif save_path.endswith(".npz"):
        status = save_npz(
            data={
                "symbol": str(symbol),
                "excitation": excitation,
                "response": response,
            },
            save_path=save_path,
        )
    else:
        raise TypeError("save_path must have '.npy' or '.npz' extension.")

    return status


def save_npz(
    data: Union[Dict[str, Union[str, "Node", "NodeList", np.ndarray]], np.ndarray],
    save_path: str,
) -> bool:
    """
    Saves a dictionary of numpy arrays to an NPZ file on disk.

    :param data: Dictionary containing 'symbol', 'excitation', and 'response' key-value pairs
    :param save_path: Full path to the destination file
    :return: Boolean indicating success status of the save operation
    """
    try:
        np.savez(save_path, **data)
        return True
    except Exception as e:
        print(f"Error saving NPZ file: {e}")
        return False


def save_npy(
    data: Union[Dict[str, Union[str, "Node", "NodeList", np.ndarray]], np.ndarray],
    save_path: str,
) -> bool:
    """
    Saves data to an NPY file on disk.

    :param data: Dictionary containing 'symbol', 'excitation', and 'response' key-value pairs
    :param save_path: Full path to the destination file
    :return: Boolean indicating success status of the save operation
    """
    try:
        np.save(file=save_path, arr=data)
        return True
    except Exception as e:
        print(f"Error saving NPY file: {e}")
        return False


def load_s2data(
    data_path: str,
) -> Union[
    Tuple[
        Union[str, "Node", "NodeList"],
        Union[int, bool, float, np.ndarray],
        Union[int, bool, float, np.ndarray],
    ],
    None,
]:
    """
    Loads S2 data (symbolic expressions and time series) previously saved with save_s2data.

    :param data_path: Path to the data file or directory containing 's2data.npz'
    :return: Tuple containing (symbol, excitation, response) or None if loading fails
    :raises FileNotFoundError: If the specified file or directory doesn't exist
    :raises TypeError: If the file format is not supported
    """
    # Check if path exists
    if not path.exists(data_path):
        raise FileNotFoundError(f"File {data_path} not found.")

    # Load based on file type
    if data_path.endswith(".npy"):
        data = load_npy(data_path)
    elif data_path.endswith(".npz"):
        data = load_npz(data_path)
    elif path.isdir(data_path):
        # Handle directory input
        data_path = path.join(data_path, "s2data.npz")
        if path.exists(data_path):
            data = load_npz(data_path)
        else:
            raise FileNotFoundError(f"File {data_path} not found.")
    else:
        raise TypeError(
            "data_path must have '.npy' or '.npz' extension or be a directory."
        )

    if data is None:
        return None

    return data["symbol"], data["excitation"], data["response"]


def load_npy(
    data_path: str,
) -> Union[Dict[str, Union[str, "Node", "NodeList", np.ndarray]], None]:
    """
    Loads data from an NPY file.

    :param data_path: Path to the NPY file
    :return: Dictionary containing the loaded data or None if loading fails
    """
    try:
        data = np.load(data_path, allow_pickle=True)
        return data.tolist()
    except Exception as e:
        print(f"Error loading NPY file: {e}")
        return None


def load_npz(
    data_path: str,
) -> Union[Dict[str, Union[str, "Node", "NodeList", np.ndarray]], None]:
    """
    Loads data from an NPZ file.

    :param data_path: Path to the NPZ file
    :return: Dictionary containing the loaded data or None if loading fails
    """
    try:
        data = np.load(data_path)
        return data
    except Exception as e:
        print(f"Error loading NPZ file: {e}")
        return None


def is_all_zeros(arr: np.ndarray) -> Union[bool, bool_, None, np.ndarray]:
    """
    Determine whether the input array is all 0.

    :param arr: Array to be checked.
    :return: Boolean indicating success status of the check.
    """
    return np.all(arr == 0)


def z_score_normalization(x: np.ndarray) -> Union[np.ndarray, None]:
    """
    Perform Z-score normalization on the input time series.

    :param x: Input two-dimensional time series with [n_points, n_dims] in NumPy.
    :return: Normalized time series with origin shape.
    """
    if is_all_zeros(x):
        # Make sure the input array is not all 0
        return None
    elif np.isinf(x).any():
        # Make sure the input array does not contain infinity
        return None
    elif np.isnan(x).any():
        # Ensure that the input array does not contain NaN values
        return None
    else:
        # Normalize array alignment for normal value range
        return (x - np.mean(x, axis=0, keepdims=True)) / np.std(
            x, axis=0, keepdims=True
        )


def max_min_normalization(x: np.ndarray) -> Union[np.ndarray, None]:
    """
    Perform min-max normalization on the input time series.

    :param x: Input two-dimensional time series with [n_points, n_dims] in NumPy.
    :return: Normalized time series with origin shape.
    """
    if is_all_zeros(x):
        # Make sure the input array is not all 0
        return None
    elif np.isinf(x).any():
        # Make sure the input array does not contain infinity
        return None
    elif np.isnan(x).any():
        # Ensure that the input array does not contain NaN values
        return None
    else:
        # Normalize array alignment for normal value range
        return (x - np.min(x, axis=0, keepdims=True)) / (
            np.max(x, axis=0, keepdims=True) - np.min(x, axis=0, keepdims=True)
        )


def fft(
    array: np.ndarray, axis: Optional[int] = None, norm: Optional[str] = "backward"
) -> np.ndarray:
    """
    Performs a Fast Fourier Transform on the input time series data.

    :param array: Input two-dimensional time series with [n_points, n_dims].
    :param axis: Axis over which to compute the FFT.  If not given, the last axis is.
    :param norm: Normalization method to use.  Can be "backward", "forward" or "ortho".

    :return: The transformed results for the input time series in freq domain.
    """
    # Handling data types
    array = np.asarray(array)

    # If the user specifies the dimensions of the operation
    if axis is not None:
        return np_fft.fft(array, axis=axis, norm=norm)

    else:
        # Determine the dimension of the data
        shape = array.shape
        if len(shape) == 2:
            # Input data is a multi-channel time series
            return np_fft.fft(array, axis=0, norm=norm)
        elif len(shape) == 1:
            # The input data is a single-channel time series
            return np_fft.fft(array, norm=norm)
        else:
            raise NotImplementedError


def ifft(
    array: np.ndarray, axis: Optional[int] = None, norm: Optional[str] = "backward"
) -> np.ndarray:
    """
    Perform inverse fast Fourier transform on the input frequency domain signal.

    :param array: Input two-dimensional time series with [n_points, n_dims] in freq domain.
    :param axis: Axis over which to compute the FFT.  If not given, the last axis is.
    :param norm: Normalization method to use.  Can be "backward", "forward" or "ortho".

    :return: The transformed results for the input time series in time domain.
    """
    # Handling data types
    array = np.asarray(array)

    # If the user specifies the dimensions of the operation
    if axis is not None:
        return np_fft.ifft(array, axis=axis, norm=norm)

    else:
        # Determine the dimension of the data
        shape = array.shape
        if len(shape) == 2:
            # Input data is a multi-channel time series
            return np_fft.ifft(array, axis=0, norm=norm)
        elif len(shape) == 1:
            # The input data is a single-channel time series
            return np_fft.ifft(array, norm=norm)
        else:
            raise NotImplementedError


def fftshift(array: np.ndarray) -> np.ndarray:
    """
    Decenter the result in the frequency domain before inverse fast Fourier transform.

    :param array: The results of the FFT.

    :return: Frequency domain result after fast Fourier transform centering.
    """
    return np_fft.fftshift(array)


def ifftshift(array: np.ndarray) -> np.ndarray:
    """
    Decenter the result in the frequency domain before inverse fast Fourier transform.

    :param array: The inputs before the iFFT.

    :return: Frequency domain representation after decentralized restoration.
    """
    return np_fft.ifftshift(array)


def generate_arma_samples(
    num_samples: int,
    seq_len: int,
    phi1: float = 0.6,
    theta1: float = -0.4,
    sigma: float = 0.5,
    return_params: bool = False,
) -> Union[np.ndarray, Tuple[np.ndarray, float, float, float]]:
    """
    Generate ARMA(1,1) stationary time series samples of shape [num_samples, seq_len].

    :param num_samples: Number of samples to generate.
    :param seq_len: Length of each time series sample.
    :param phi1: AR(1) coefficient.
    :param theta1: MA(1) coefficient.
    :param sigma: Standard deviation of the white noise.
    :param return_params: Whether to return the parameters used for generation.

    :return: Generated samples of shape [num_samples, seq_len]. If return_params is True, also returns the parameters (phi1, theta1, sigma).
    """
    samples = []
    for _ in range(num_samples):
        # Initialize white noise (excitation source) and time series
        eps = np.random.normal(0, sigma, seq_len)  # White noise sequence
        x = np.zeros(seq_len)
        x[0] = eps[0]  # Initial value

        # Recursively generate ARMA(1,1) sequence: Xt = phi1*Xt-1 + eps_t - theta1*eps_t-1
        for t in range(1, seq_len):
            x[t] = phi1 * x[t - 1] + eps[t] - theta1 * eps[t - 1]
        samples.append(x)

    # Return generated samples and parameters
    if return_params:
        return np.array(samples), (phi1, theta1, sigma)
    return np.array(samples)


def generate_nonstationary_sine(
    num_samples: int,
    seq_len: int,
    freq: float = 2.0,
    sample_rate: Union[int, float] = 100,
    amp: float = 1.5,
    return_params: bool = False,
) -> Union[np.ndarray, Tuple[np.ndarray, float, Union[int, float]]]:
    """Generate non-stationary sine signals with linear trend of shape [num_samples, seq_len].

    :param num_samples: Number of samples to generate.
    :param seq_len: Length of each time series sample.
    :param freq: Frequency of the sine wave.
    :param sample_rate: Sampling rate of the time series.
    :param amp: Amplitude of the sine wave.
    :param return_params: Whether to return the parameters used for generation.

    :return: Generated non-stationary sine wave samples of shape [num_samples, seq_len], frequency, and sample rate.
    """
    t = np.linspace(0, seq_len / sample_rate, seq_len, endpoint=False)
    nonstationary_samples = []

    for _ in range(num_samples):
        phase = np.random.uniform(0, 2 * np.pi)

        # Sine signal + linear trend (causing non-stationarity) + small noise
        sine_seq = amp * np.sin(2 * np.pi * freq * t + phase)

        # Linear trend: increases over time, core source of non-stationarity
        trend = 0.1 * t
        noise = np.random.normal(0, 0.05, seq_len)
        nonstationary_seq = sine_seq + trend + noise
        nonstationary_samples.append(nonstationary_seq)

    # Return generated samples and parameters
    if return_params:
        return np.array(nonstationary_samples), freq, sample_rate
    return np.array(nonstationary_samples)


def eacf_rlike(
    time_series: Union[np.ndarray, list, pd.Series], max_ar: int = 5, max_ma: int = 5
) -> Tuple[np.ndarray, float, pd.DataFrame]:
    """
    This code replicates the calculation of the EACF function in the TSA library of R to identify the order of the ARMA(p, q) model.

    :param time_series: Input time series data, which can be a NumPy array, list, or Pandas Series.
    :param max_ar: The highest AR order.
    :param max_ma: The highest MA order.

    :return: An EACF matrix, where rows represent AR order p and columns represent MA order q.
    """
    from statsmodels.tsa.arima.model import ARIMA
    from statsmodels.tsa.stattools import acf

    # Step 1: Mean removal from the sequence (preprocessing for R alignment)
    time_series = np.asarray(time_series)
    series_centered = time_series - np.mean(time_series)
    n = len(series_centered)
    threshold = 1.96 / np.sqrt(n)  # R default 95% confidence threshold

    # Step 2: Initialize EACF matrix (rows=p(0~max_ar), columns=q(1~max_ma))
    eacf_matrix = np.zeros((max_ar + 1, max_ma))

    for p in range(max_ar + 1):  # Iterate over each AR order p
        # Step 3: Fit AR(p) and calculate residuals
        if p == 0:
            # For p=0, no AR model is fitted, so residuals are just the mean-centered series (aligning with R's approach)
            residuals = series_centered
        else:
            # Fit AR(p) model (aligning with R's arima method, using MLE)
            try:
                ar_model = ARIMA(series_centered, order=(p, 0, 0), trend="n")
                ar_result = ar_model.fit(method="innovations_mle")
                residuals = ar_result.resid
            except:
                residuals = np.zeros_like(series_centered)

        # Step 4: Calculate ACF of residuals (align with R's acf: unbiased=False, plot=FALSE)
        # R's ACF (Acceptable Functionality) is biased by default, corresponding to `adjusted=False` in statsmodels.
        acf_vals = acf(
            residuals,
            nlags=max_ma,
            fft=False,
            adjusted=False,  # Key: Align with R's biased ACF
            alpha=None,
        )

        # Step 5: Fill the EACF matrix (the lag1~lag_max_q of the ACF correspond to q=1~max_ma).
        eacf_matrix[p, :] = acf_vals[1 : (max_ma + 1)]  # Skip lag0 (always 1)

    # Formatted output (for easy comparison of R results)
    eacf_df = pd.DataFrame(
        eacf_matrix,
        index=[f"p={p}" for p in range(max_ar + 1)],
        columns=[f"q={q}" for q in range(1, max_ma + 1)],
    )

    return eacf_matrix, threshold, eacf_df


def yule_walker(A: np.ndarray) -> Tuple[np.ndarray, Union[float, np.ndarray]]:
    """
    Solving the Yule-Walker equations yields the parameters of the AR model.

    The Yule-Walker equations can be expressed in matrix form as::

    r(0)*1 + r(1)*a[1] + r(2)*a[2] + ... + r(n)*a[n]       = σ²
    r(1)*1 + r(0)*a[1] + r(1)*a[2] + ... + r(n-1)*a[n]     = 0
    r(2)*1 + r(1)*a[1] + r(0)*a[2] + ... + r(n-2)*a[n]     = 0
    ...
    r(n-1)*1 + r(n-2)*a[1] + r(n-3)*a[2] + ... + r(1)*a[n] = 0
    r(n)*1 + r(n-1)*a[1] + r(n-2)*a[2] + ... + r(0)*a[n]   = 0

    Where r(k) is the value of the autocorrelation function at lag k,
    a[i] are the coefficients of the AR model, and σ² is the variance of the noise.

    This equation can be derived based on the orthogonality principle,
    representing the relationship between the parameters of the AR model and the autocorrelation function of the sequence.

    :param A: The matrix representing the Yule-Walker equations, where the first row corresponds to the equation for σ² and the subsequent rows correspond to the equations for a1~an.

    :return: A tuple containing the vector of AR coefficients (a1~an) and the variance of the noise (σ²).
    """
    # Check if A is a ndarray and has the correct shape
    if not isinstance(A, np.ndarray):
        raise ValueError("Input A must be a numpy array.")
    if A.shape[0] < 2 or A.shape[1] < 2:
        raise ValueError(
            "Input A must have at least 2 rows and 2 columns to solve for a1~an and σ²."
        )

    # Check if the matrix A is square
    if A.shape[0] != A.shape[1]:
        raise ValueError("Input A must be a square matrix.")

    # Solve for the coefficients using the equations from the second line onwards.
    B = A[1:, 1:]  # Extracting the coefficient matrix
    c = -A[1:, 0]  # Extract the constant term and take its negative.

    try:
        # Solve for a1~an
        a = np.linalg.solve(B, c)

    except np.linalg.LinAlgError as e:
        print(f"Solution failed: {e}")
        print(
            "Reason: Matrix B is not invertible, and therefore cannot uniquely determine a1~an."
        )

        # If B is not invertible, we can use least squares to find an approximate solution.
        a = np.linalg.lstsq(B, c, rcond=None)[0]

    # Solve for σ² using the first line of the equations
    x = np.hstack([1, a])  # Construct the x vector
    sigma_sq = np.dot(A[0], x)

    return x, sigma_sq
