# -*- coding: utf-8 -*-
"""
This module is used to generate stimulus time series data for input into complex systems (symbolic expressions).
It primarily includes five different generation methods:

- [`MixedDistribution`](https://github.com/wwhenxuan/S2Generator/blob/main/S2Generator/excitation/mixed_distribution.py);
- [`AutoregressiveMovingAverage`](https://github.com/wwhenxuan/S2Generator/blob/main/S2Generator/excitation/autoregressive_moving_average.py);
- [`ForecastPFN`](https://github.com/wwhenxuan/S2Generator/blob/main/S2Generator/excitation/forecast_pfn.py);
- [`KernelSynth`](https://github.com/wwhenxuan/S2Generator/blob/main/S2Generator/excitation/kernel_synth.py);
- [`IntrinsicModeFunction`](https://github.com/wwhenxuan/S2Generator/blob/main/S2Generator/excitation/intrinsic_mode_functions.py);

Detailed hyperparameter configuration is provided for each method.
Each method can also generate time series data by passing a random number
generator to the __call__ method or the generate method.

To ensure unified calling, we further encapsulate these five methods into Excitation,
and provide a unified SeriesParams object for parameter management.

Created on 2025/08/13 23:47:59
@author: Whenxuan Wang
@email: wwhenxuan@gmail.com
@url: https://github.com/wwhenxuan/S2Generator
"""
__all__ = [
    "MixedDistribution",
    "AutoregressiveMovingAverage",
    "ForecastPFN",
    "KernelSynth",
    "IntrinsicModeFunction",
    "Excitation",
]

# Generate stimulus time series by sampling from mixed distributions
from .mixed_distribution import MixedDistribution

# Generate stimulus time series by constructing an autoregressive moving average process
from .autoregressive_moving_average import AutoregressiveMovingAverage

# Generate stimulus time series by simulating trend, period, and noise components of time series data
from .forecast_pfn import ForecastPFN

# Generate stimulus time series through Kernel Synth of multiple kernel operations
from .kernel_synth import KernelSynth

# The excitation time series is generated by constructing the highly periodic
# intrinsic mode function from the perspective of signal decomposition
from .intrinsic_mode_functions import IntrinsicModeFunction

# Generic interface for generating stimulus time series data
from ._interface import Excitation
