# -*- coding: utf-8 -*-
"""
Created on 2026/06/21 01:34:30
@author: Whenxuan Wang
@email: wwhenxuan@gmail.com
@url: https://github.com/wwhenxuan/S2Generator
"""

from typing import Optional, Tuple, Dict, Any

import sys
from pathlib import Path

if __package__ is None or __package__ == "":
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import numpy as np
from scipy.linalg import toeplitz
from statsmodels.tsa.stattools import acf

from s2generator.utils._tools import yule_walker
from s2generator.simulator.low_pass_filter import (
    maybe_attach_lowpass,
    maybe_apply_lowpass,
)


class KalmanFilterSimulator(object):
    """
    Simulate new time series using a state-space AR model estimated and driven by a Kalman filter.

    Any stationary signal can be viewed as the response obtained by exciting a linear system with white noise.

    This module learns a state-space representation of the input series and uses the Kalman filter to characterize
    the one-step prediction (innovation) structure. New sequences are generated by exciting the learned linear
    dynamical system with white process noise.

    The underlying model is an AR(p) process written in companion state-space form::

        x_t = F x_{t-1} + G w_t,    w_t ~ N(0, σ²)
        y_t = H x_t

    where the state vector stores recent lags of the output. The AR coefficients and process noise variance σ² are
    obtained from the Yule-Walker equations (equivalently, autocorrelation matching), while the Kalman filter is
    used during fitting to compute innovations and during generation to propagate the latent state forward under
    white-noise excitation.

    Compared with the Wiener-filter simulator (which applies ``scipy.signal.lfilter`` on white noise), this module
    exposes the same white-noise-to-signal mapping through an explicit state-space / Kalman-filtering formulation,
    which is the standard tool in modern signal processing and complex-system modeling for recursive estimation
    and simulation of linear Gaussian dynamical systems.
    """

    def __init__(
        self,
        state_order: int = 6,
        revin: Optional[bool] = True,
        random_state: Optional[int] = 42,
        observation_noise: float = 1e-8,
        lowpass: bool = False,
        lowpass_kwargs: Optional[Dict[str, Any]] = None,
    ) -> None:
        """
        :param state_order: Length of the AR coefficient vector (including ``a₀ = 1``),
                            consistent with ``filter_order`` in ``WienerFilterSimulator``.
                            The latent state dimension is ``state_order - 1``.
        :param revin: Whether to perform reversible normalization (keep the variance of the input sequence unchanged).
        :param random_state: The random seed for reproducibility.
        :param observation_noise: Diagonal observation-noise variance R used in the Kalman update during fitting.
                                  A tiny positive value avoids numerical singularity when R = 0.
        :param lowpass: Whether to apply low-pass post-processing after ``transform``.
        :param lowpass_kwargs: Optional kwargs forwarded to ``LowPassFilter``.

        :return: None
        """
        self.state_order = state_order
        self.lag_max = state_order * 2

        self.acf_vals = None
        self.R_autocorr = None

        self._sigma_sq = None
        self._coeffs = None

        self._F = None
        self._G = None
        self._H = None
        self._Q = None
        self._R = None

        self.revin = revin
        self.mean, self.std = None, None

        self.random_state = random_state
        self.rng = np.random.RandomState(seed=random_state)

        self.observation_noise = observation_noise

        self.lowpass = lowpass
        self.lowpass_kwargs = lowpass_kwargs
        self._lowpass_filter = None

        self.time_series = None
        self.time_series_trimmed = None

        self.innovations = None
        self.residuals = None

        self.simulated_series = None

    def fit(self, time_series: np.ndarray) -> None:
        """
        Fit the state-space AR model and run the Kalman filter on the input series.

        AR parameters are estimated with the Yule-Walker method; the companion matrices ``F, G, H, Q, R`` are then
        constructed and a Kalman filter pass yields the innovation sequence.

        :param time_series: The input time series to fit, with shape 1D [seq_len, ] or 2D [num_samples, seq_len].

        :return: None
        """
        time_series = self.check_inputs(time_series)
        self.time_series = time_series

        if self.revin:
            self.mean = np.mean(time_series)
            self.std = np.std(time_series)
            time_series = (time_series - self.mean) / self.std

        self.acf_vals = self.acf(time_series=time_series)
        self.R_autocorr = toeplitz(self.acf_vals[: self.state_order])

        self._coeffs, self._sigma_sq = yule_walker(A=self.R_autocorr)
        self._build_state_space()

        self.innovations = self._kalman_filter(observations=time_series)
        self.time_series_trimmed = time_series[self.state_order :]
        self.residuals = self.innovations[self.state_order :]

        white_noise = self.rng.normal(
            0,
            scale=np.sqrt(self.sigma_sq),
            size=len(time_series) + self.state_order,
        )
        reconstructed = self.invoke(white_noise=white_noise)
        self.residuals = time_series - reconstructed

        maybe_attach_lowpass(
            self,
            enabled=self.lowpass,
            kwargs=self.lowpass_kwargs,
            reference=self.time_series,
        )

    def transform(
        self, num_samples: int, seq_len: int, random_state: Optional[int] = None
    ) -> np.ndarray:
        """
        Generate new time series by exciting the fitted state-space model with white process noise.

        :param num_samples: The number of new time series to generate.
        :param seq_len: The length of each generated time series.
        :param random_state: The random seed for reproducibility. If None, uses the instance random state.

        :return: The generated time series with shape [num_samples, seq_len].
        """
        if self._coeffs is None:
            raise ValueError(
                "The state-space model has not been fitted yet; please call the `fit` method first."
            )

        if random_state is not None:
            rng = np.random.RandomState(seed=random_state)
        else:
            rng = self.rng

        white_noise = rng.normal(
            0,
            scale=np.sqrt(self.sigma_sq),
            size=(num_samples, seq_len + self.state_order),
        )

        simulated_series = np.zeros(shape=(num_samples, seq_len))
        for i in range(num_samples):
            simulated_series[i, :] = self.invoke(white_noise=white_noise[i, :])

        if self.revin:
            self.simulated_series = simulated_series * self.std + self.mean
        else:
            self.simulated_series = simulated_series

        self.simulated_series = maybe_apply_lowpass(self, self.simulated_series)
        return self.simulated_series

    def invoke(self, white_noise: np.ndarray) -> np.ndarray:
        """
        Generate a sequence by driving the state equation with a supplied white-noise excitation.

        :param white_noise: Input white-noise sequence with shape 1D [seq_len + state_order, ].

        :return: Generated time series with shape 1D [seq_len, ].
        """
        if self._coeffs is None:
            raise ValueError(
                "The state-space model has not been fitted yet; please call the `fit` method first."
            )

        simulated_series = self._simulate_state_space(white_noise=white_noise)
        return simulated_series[self.state_order :]

    def acf(
        self,
        time_series: np.ndarray,
        lag_max: Optional[int] = None,
        fft: Optional[bool] = True,
    ) -> np.ndarray:
        """
        Calculate the autocorrelation function (ACF) of the input time series.

        :param time_series: Input series with shape 1D [seq_len, ].
        :param lag_max: Maximum lag. Defaults to ``self.lag_max`` (``state_order * 2``).
        :param fft: Whether to use FFT for ACF computation.

        :return: ACF values for lags 0 through lag_max, shape [lag_max + 1, ].
        """
        return acf(
            time_series, nlags=self.lag_max if lag_max is None else lag_max, fft=fft
        )

    def check_inputs(self, time_series: np.ndarray) -> np.ndarray:
        """
        Check the format and length of the input time series.

        :param time_series: Input with shape 1D [seq_len, ] or 2D [num_samples, seq_len].

        :return: Validated 1D time series with shape [seq_len, ].
        """
        if not isinstance(time_series, np.ndarray):
            raise ValueError("The input time series must be a NumPy array.")

        if len(time_series.shape) > 2:
            raise ValueError(
                "The input time series must be 1D with [seq_len, ] or 2D with "
                "[num_samples, seq_len], but got shape: {}".format(time_series.shape)
            )

        if len(time_series.shape) == 2:
            time_series = time_series.flatten()

        if len(time_series) < 2 * self.state_order:
            raise ValueError(
                f"Input time series length must be at least {2 * self.state_order} "
                "to ensure accurate ACF estimation."
            )

        if np.isnan(time_series).any():
            raise ValueError("The input time series must not contain NaN values.")

        if np.std(time_series) < 1e-8:
            raise ValueError(
                "The time series variance is 0 (all values are the same), "
                "making it impossible to fit the state-space model."
            )

        return time_series

    def set_coeffs(self, coeffs: np.ndarray) -> None:
        """
        Manually set the AR coefficients (for testing purposes).

        :param coeffs: AR coefficients with shape 1D [state_order, ], including the leading 1.

        :return: None
        """
        assert isinstance(coeffs, np.ndarray), "Coefficients must be a NumPy array."
        assert (
            len(coeffs) == self.state_order
        ), f"Length of coefficients must be equal to state_order ({self.state_order})."
        self._coeffs = coeffs
        if self._sigma_sq is not None:
            self._build_state_space()

    def set_sigma_sq(self, sigma_sq: float) -> None:
        """
        Manually set the process noise variance σ² (for testing purposes).

        :param sigma_sq: Positive process-noise variance.

        :return: None
        """
        assert isinstance(
            sigma_sq, (int, float, np.ndarray)
        ), "Noise variance σ² must be a numeric value."
        assert sigma_sq > 0, "Noise variance σ² must be a positive float."

        if isinstance(sigma_sq, np.ndarray):
            assert sigma_sq.shape == (), "Noise variance σ² must be a scalar value."

        self._sigma_sq = np.asarray(sigma_sq, dtype=np.float64)
        if self._coeffs is not None:
            self._build_state_space()

    @property
    def coeffs(self) -> np.ndarray:
        """Get the AR coefficients after fitting."""
        if self._coeffs is None:
            raise ValueError(
                "The AR coefficients have not been calculated yet; please call the `fit` method first."
            )
        return self._coeffs

    @property
    def sigma_sq(self) -> float:
        """Get the process noise variance σ² after fitting."""
        if self._sigma_sq is None:
            raise ValueError(
                "The process noise variance has not been calculated yet; please call the `fit` method first."
            )
        return self._sigma_sq

    @property
    def state_space_matrices(
        self,
    ) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, float]:
        """
        Return the fitted state-space matrices ``(F, G, H, Q, R)``.

        :return: Tuple of transition matrix, input matrix, observation matrix, process-noise
                 covariance, and observation-noise variance.
        """
        if self._F is None:
            raise ValueError(
                "The state-space model has not been fitted yet; please call the `fit` method first."
            )
        return self._F, self._G, self._H, self._Q, self._R

    def _build_state_space(self) -> None:
        """
        Construct companion-form state-space matrices from fitted AR coefficients.

        The coefficient vector is ``coeffs = [1, φ₁, ..., φ_p]`` (length ``state_order``),
        corresponding to AR order ``p = state_order - 1``. The companion state dimension is ``p``.
        The innovation form is ``y_t + φ₁ y_{t-1} + ... + φ_p y_{t-p} = w_t``.
        """
        phi = self._coeffs[1:]
        p = len(phi)

        self._F = np.zeros((p, p), dtype=np.float64)
        self._F[0, :] = -phi
        if p > 1:
            self._F[1:, :-1] = np.eye(p - 1)

        self._G = np.zeros((p, 1), dtype=np.float64)
        self._G[0, 0] = 1.0

        self._H = np.zeros((1, p), dtype=np.float64)
        self._H[0, 0] = 1.0

        self._Q = self._sigma_sq * (self._G @ self._G.T)
        self._R = float(self.observation_noise)

    def _kalman_filter(self, observations: np.ndarray) -> np.ndarray:
        """
        Run a scalar-measurement Kalman filter and return the innovation sequence.

        :param observations: Observed time series, shape [n_obs, ].

        :return: Innovations (one-step prediction errors), shape [n_obs, ].
        """
        n_obs = len(observations)
        p = self._F.shape[0]

        F = self._F
        G = self._G
        H = self._H
        Q = self._Q
        R = self._R

        x = np.zeros(p, dtype=np.float64)
        P = np.eye(p, dtype=np.float64)
        innovations = np.zeros(n_obs, dtype=np.float64)

        H_row = H[0]

        for t in range(n_obs):
            x_pred = F @ x
            P_pred = F @ P @ F.T + Q

            y_pred = H_row @ x_pred
            innovation = observations[t] - y_pred
            S = H_row @ P_pred @ H_row + R

            K = P_pred @ H_row / S
            x = x_pred + K * innovation
            P = P_pred - np.outer(K, H_row) @ P_pred

            innovations[t] = innovation

        return innovations

    def _simulate_state_space(self, white_noise: np.ndarray) -> np.ndarray:
        """
        Forward-simulate the state equation under white-noise excitation.

        :param white_noise: Process noise sequence, shape [seq_len, ].

        :return: Output sequence before edge trimming, shape [seq_len, ].
        """
        n_steps = len(white_noise)
        p = self._F.shape[0]

        F = self._F
        G = self._G.ravel()

        x = np.zeros(p, dtype=np.float64)
        output = np.zeros(n_steps, dtype=np.float64)

        for t in range(n_steps):
            x = F @ x + G * white_noise[t]
            output[t] = x[0]

        return output


if __name__ == "__main__":
    import matplotlib.pyplot as plt

    from s2generator.utils.visualization import plot_simulator_statistics

    # Generate a sine signal as the reference input.
    seq_length = 1000
    t = np.arange(seq_length)
    sine_signal = np.sin(2 * np.pi * t / 50) + 0.05 * np.random.randn(seq_length)

    simulator = KalmanFilterSimulator(state_order=8, revin=True, random_state=42)
    simulator.fit(sine_signal)

    generated = simulator.transform(num_samples=1, seq_len=seq_length, random_state=7)[
        0
    ]

    print("KalmanFilterSimulator fit summary")
    print(f"  state_order : {simulator.state_order}")
    print(f"  sigma_sq    : {simulator.sigma_sq:.6f}")
    print(f"  coeffs      : {np.array2string(simulator.coeffs, precision=4)}")

    fig = plot_simulator_statistics(
        original_series=sine_signal,
        generated_series=generated,
        residuals=simulator.residuals,
        nlags=50,
        nperseg=128,
    )
    fig.suptitle(
        "KalmanFilterSimulator: Sine Signal Test",
        fontsize=14,
        fontweight="bold",
        y=1.01,
    )
    plt.show()
