# -*- coding: utf-8 -*-
"""
Created on 2026/06/21 12:01:43
@author: Whenxuan Wang
@email: wwhenxuan@gmail.com
@url: https://github.com/wwhenxuan/S2Generator
"""

from typing import Union, Optional, Tuple, List, Dict, Any

import numpy as np
import pandas as pd
from statsmodels.tsa.regime_switching.markov_autoregression import (
    MarkovAutoregression,
)
from statsmodels.stats.diagnostic import acorr_ljungbox
from s2generator.simulator.low_pass_filter import (
    maybe_attach_lowpass,
    maybe_apply_lowpass,
)

import warnings

warnings.filterwarnings("ignore")


class MarkovSwitchingSimulator(object):
    """
    Simulate time series data using a Markov switching autoregression (MSAR) model.

    Any stationary signal can be viewed as the response obtained by exciting a linear system
    with white noise. When the statistical properties of the input sequence change over time,
    a single global AR/ARIMA model may be insufficient. The MSAR model extends the white-noise
    excitation viewpoint by introducing a **latent Markov regime** that switches among several
    local autoregressive dynamics.

    The fitted model can be written as::

        y_t = a_{S_t} + sum_{j=1}^{p} phi_{j, S_t} (y_{t-j} - a_{S_{t-j}}) + epsilon_t,
        epsilon_t ~ N(0, sigma_{S_t}^2),
        P(S_t = j | S_{t-1} = i) = P[i, j]

    where S_t in {0, ..., K-1} is the hidden regime. Fitting is performed with the Hamilton
    filter / maximum likelihood procedure implemented in ``statsmodels``. New sequences are
    generated by simulating both the Markov regime path and the regime-specific Gaussian
    innovations, then propagating the switching autoregressive recursion forward in time.

    Compared with ``ARIMASimulator``, ``WienerFilterSimulator``, and ``KalmanFilterSimulator``,
    this simulator is better suited to time series whose mean, variance, or local autocorrelation
    structure changes across segments, while preserving the same ``fit`` / ``transform`` interface.
    """

    def __init__(
        self,
        max_k_regimes: int = 2,
        max_order: int = 3,
        trend: str = "c",
        switching_ar: Union[bool, List[bool]] = True,
        switching_trend: Union[bool, List[bool]] = True,
        switching_variance: bool = False,
        signif: float = 0.05,
        not_white_alarm: bool = False,
        revin: bool = True,
        random_state: Optional[int] = 42,
        maxiter: int = 200,
        lowpass: bool = False,
        lowpass_kwargs: Optional[Dict[str, Any]] = None,
    ) -> None:
        """
        :param max_k_regimes: Maximum number of latent regimes to consider when fitting or searching orders.
        :param max_order: Maximum autoregressive order ``p`` to consider when fitting or searching orders.
        :param trend: Trend specification passed to ``MarkovAutoregression`` (``'n'``, ``'c'``, ``'t'``, ``'ct'``).
        :param switching_ar: Whether AR coefficients switch across regimes.
        :param switching_trend: Whether intercept / trend coefficients switch across regimes.
        :param switching_variance: Whether the innovation variance switches across regimes.
        :param signif: Significance level used in residual diagnosis.
        :param not_white_alarm: Whether to raise an error when residuals fail the white-noise test.
        :param revin: Whether to apply reversible normalization before fitting and inverse transform after generation.
        :param random_state: Random seed for reproducible simulation.
        :param maxiter: Maximum number of iterations for the statsmodels MLE optimizer.
        :param lowpass: Whether to apply low-pass post-processing after ``transform``.
        :param lowpass_kwargs: Optional kwargs forwarded to ``LowPassFilter``.

        :return: None
        """
        self.max_k_regimes = max_k_regimes
        self.max_order = max_order
        self.trend = trend
        self.switching_ar = switching_ar
        self.switching_trend = switching_trend
        self.switching_variance = switching_variance
        self.signif = signif
        self.not_white_alarm = not_white_alarm
        self.revin = revin
        self.random_state = random_state
        self.maxiter = maxiter

        self.lowpass = lowpass
        self.lowpass_kwargs = lowpass_kwargs
        self._lowpass_filter = None

        # Normalization statistics for reversible scaling
        self.mean, self.std = None, None

        # Selected model orders after fitting
        self.k_regimes = None
        self.order = None

        # Underlying statsmodels model and fitted result object
        self.msar_model = None
        self.model = None

        # Residuals and smoothed regime probabilities from the fitted model
        self.residuals = None
        self.smoothed_probabilities = None

        # Generated samples from the latest transform call
        self.simulated_series = None
        self.time_series = None

    def fit(
        self, time_series: np.ndarray, select_order: Optional[bool] = False
    ) -> None:
        """
        Fit a Markov switching autoregression model to the input time series.

        :param time_series: Input series with shape 1D [seq_len, ] or 2D [num_samples, seq_len].
        :param select_order: If True, select ``(k_regimes, order)`` by BIC over the search grid.

        :return: None
        """
        # Validate and flatten the input sequence
        time_series = self.check_inputs(time_series=time_series)
        endog = np.asarray(time_series, dtype=np.float64)
        self.time_series = endog.copy()

        # Optionally normalize the series while recording mean and std for inverse transform
        if self.revin:
            self.mean = np.mean(endog)
            self.std = np.std(endog)
            endog = (endog - self.mean) / self.std

        if select_order:
            # Search the best (k_regimes, order) pair using BIC
            self.k_regimes, self.order = self.select_msar_order(endog=endog)
        else:
            self.k_regimes = self.max_k_regimes
            self.order = self.max_order

        # Build and fit the Markov switching autoregression model
        self.msar_model = MarkovAutoregression(
            endog=endog,
            k_regimes=self.k_regimes,
            order=self.order,
            trend=self.trend,
            switching_ar=self.switching_ar,
            switching_trend=self.switching_trend,
            switching_variance=self.switching_variance,
        )
        self.model = self.msar_model.fit(disp=False, maxiter=self.maxiter)

        # Store residuals and smoothed regime probabilities for diagnosis / inspection
        self.residuals = np.asarray(self.model.resid)
        self.smoothed_probabilities = np.asarray(
            self.model.smoothed_marginal_probabilities
        )

        # Perform residual diagnosis on the fitted model
        mean_p_value, is_white = self.residual_diagnosis(signif=self.signif)
        if not is_white and self.not_white_alarm:
            raise ValueError(
                "Warning: Model residuals may not be white noise "
                f"(mean p-value={mean_p_value:.4f} < significance level={self.signif}), "
                "please re-evaluate the regime count or autoregressive order."
            )

        maybe_attach_lowpass(
            self,
            enabled=self.lowpass,
            kwargs=self.lowpass_kwargs,
            reference=self.time_series,
        )

    def transform(
        self, num_samples: int, seq_len: int, random_state: Optional[int] = None
    ) -> np.ndarray:
        """
        Generate new time series by simulating the fitted MSAR dynamics.

        Each sample is produced by drawing a Markov regime path and regime-specific
        Gaussian innovations, then propagating the switching autoregressive recursion.

        :param num_samples: Number of independent sample paths to generate.
        :param seq_len: Length of each generated sequence.
        :param random_state: Random seed for reproducibility. Uses the instance seed if None.

        :return: Generated series with shape [num_samples, seq_len].
        """
        if self.model is None:
            raise ValueError(
                "The model must be fitted before calling transform; please call `fit` first."
            )

        seed = random_state if random_state is not None else self.random_state
        simulated_series = np.zeros((num_samples, seq_len), dtype=np.float64)

        for i in range(num_samples):
            # Use a distinct but reproducible seed for each generated path
            sample_seed = None if seed is None else int(seed) + i
            simulated_series[i, :] = self._simulate(
                seq_len=seq_len, random_state=sample_seed
            )

        # Inverse normalization to restore the original scale of the input series
        if self.revin:
            self.simulated_series = simulated_series * self.std + self.mean
        else:
            self.simulated_series = simulated_series

        self.simulated_series = maybe_apply_lowpass(self, self.simulated_series)
        return self.simulated_series

    def select_msar_order(self, endog: np.ndarray) -> Tuple[int, int]:
        """
        Select the number of regimes and AR order using the BIC criterion.

        :param endog: One-dimensional normalized input series.

        :return: Tuple ``(k_regimes, order)`` with the lowest BIC among successfully fitted models.
        """
        best_bic = np.inf
        best_order = (1, 1)

        # Grid search over all candidate (k_regimes, order) combinations
        for k_regimes in range(1, self.max_k_regimes + 1):
            for order in range(1, self.max_order + 1):
                if len(endog) <= order + k_regimes:
                    continue
                try:
                    candidate = MarkovAutoregression(
                        endog=endog,
                        k_regimes=k_regimes,
                        order=order,
                        trend=self.trend,
                        switching_ar=self.switching_ar,
                        switching_trend=self.switching_trend,
                        switching_variance=self.switching_variance,
                    )
                    result = candidate.fit(disp=False, maxiter=self.maxiter)
                    if result.bic < best_bic:
                        best_bic = result.bic
                        best_order = (k_regimes, order)
                except Exception:
                    # Skip ill-conditioned combinations and continue the search
                    continue

        return best_order

    def residual_diagnosis(
        self, lags: int = 20, signif: float = None
    ) -> Tuple[float, bool]:
        """
        Perform a Ljung-Box white-noise test on the fitted model residuals.

        :param lags: Number of lags used in the Ljung-Box test.
        :param signif: Significance level. Defaults to ``self.signif`` when None.

        :return: Mean p-value and a boolean indicating whether all p-values exceed ``signif``.
        """
        if self.residuals is None:
            raise ValueError(
                "The model must be fitted before calling residual_diagnosis."
            )

        lb_test = acorr_ljungbox(self.residuals, lags=lags, return_df=True)
        lb_p_values = lb_test["lb_pvalue"]
        threshold = signif if signif is not None else self.signif

        return lb_p_values.mean(), np.all(lb_p_values > threshold)

    def model_summary(self) -> str:
        """
        Return the textual summary of the fitted MSAR model.

        :return: Summary string produced by statsmodels.
        """
        if self.model is None:
            raise ValueError("The model must be fitted before calling model_summary.")
        return self.model.summary().as_text()

    def check_inputs(self, time_series: Union[pd.Series, np.ndarray]) -> np.ndarray:
        """
        Check whether the input time series satisfies the modeling requirements.

        :param time_series: Input with shape 1D [seq_len, ] or 2D [num_samples, seq_len].

        :return: Validated one-dimensional ``np.ndarray``.
        """
        if not isinstance(time_series, (pd.Series, np.ndarray)):
            raise ValueError(
                "Input time series must be a pandas Series or numpy ndarray."
            )

        if len(time_series.shape) > 2:
            raise ValueError(
                "Input time series must be 1-dimensional with [seq_len, ] or "
                "2-dimensional with [num_samples, seq_len]."
            )

        # Flatten two-dimensional batch input into a single series for fitting
        if len(time_series.shape) == 2:
            time_series = time_series.flatten()

        time_series = np.asarray(time_series, dtype=np.float64)

        min_length = max(10, self.max_order + self.max_k_regimes + 2)
        if len(time_series) < min_length:
            raise ValueError(
                f"Input time series must have at least {min_length} data points."
            )

        if np.isnan(time_series).any():
            raise ValueError("Input time series must not contain NaN values.")

        if np.std(time_series) < 1e-8:
            raise ValueError(
                "The time series variance is 0 (all values are the same), "
                "making it impossible to fit the MSAR model."
            )

        return time_series

    @property
    def param_names(self) -> List[str]:
        """Return the names of the parameters in the fitted MSAR model."""
        if self.model is None:
            raise ValueError("The model must be fitted before calling param_names.")
        return self.model.model.param_names

    @property
    def params(self) -> np.ndarray:
        """Return the parameter values of the fitted MSAR model."""
        if self.model is None:
            raise ValueError("The model must be fitted before calling params.")
        return np.asarray(self.model.params)

    @property
    def param_items(self) -> List[Tuple[str, float]]:
        """Return a list of ``(parameter name, parameter value)`` tuples."""
        if self.model is None:
            raise ValueError("The model must be fitted before calling param_items.")
        return list(zip(self.param_names, self.params))

    @property
    def regime_transition(self) -> np.ndarray:
        """
        Return the fitted Markov transition probability matrix.

        The returned array has shape ``[k_regimes, k_regimes, 1]``, where entry
        ``[j, i, 0]`` denotes ``P(S_t = j | S_{t-1} = i)``.
        """
        if self.model is None:
            raise ValueError(
                "The model must be fitted before calling regime_transition."
            )
        return np.asarray(self.model.regime_transition)

    def _extract_regime_parameters(self) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        """
        Parse regime-specific intercepts, AR coefficients, and innovation variances.

        :return: Tuple ``(const, ar, variance)`` where
                 ``const`` has shape ``[k_regimes]``,
                 ``ar`` has shape ``[k_regimes, order]``,
                 ``variance`` has shape ``[k_regimes]``.
        """
        k_regimes = self.model.k_regimes
        order = self.model.order
        msar_model = self.model.model
        fitted_params = self.model.params

        const = np.zeros(k_regimes, dtype=np.float64)
        ar = np.zeros((k_regimes, order), dtype=np.float64)

        # Intercept / trend coefficients may switch across regimes
        if msar_model._k_exog > 0:
            for regime in range(k_regimes):
                const[regime] = fitted_params[msar_model.parameters[regime, "exog"]][0]

        # Autoregressive coefficients may also switch across regimes
        if order > 0:
            if np.any(msar_model.switching_ar):
                for regime in range(k_regimes):
                    ar[regime, :] = fitted_params[
                        msar_model.parameters[regime, "autoregressive"]
                    ]
            else:
                shared_ar = fitted_params[msar_model.parameters["autoregressive"]]
                for regime in range(k_regimes):
                    ar[regime, :] = shared_ar

        # Innovation variance may be shared or regime-specific
        variance = fitted_params[msar_model.parameters["variance"]]
        variance = np.atleast_1d(np.asarray(variance, dtype=np.float64)).reshape(-1)
        if variance.size == 1:
            variance = np.repeat(variance[0], k_regimes)

        return const, ar, variance

    def _simulate(self, seq_len: int, random_state: Optional[int] = None) -> np.ndarray:
        """
        Simulate a single MSAR sample path from the fitted parameters.

        The recursion follows the deviation form used by ``statsmodels``::

            y_t = a_{S_t} + sum_j phi_{j, S_t} (y_{t-j} - a_{S_{t-j}}) + epsilon_t

        :param seq_len: Length of the simulated sequence.
        :param random_state: Random seed for reproducibility.

        :return: Simulated series with shape [seq_len, ].
        """
        rng = np.random.RandomState(seed=random_state)
        k_regimes = self.model.k_regimes
        order = self.model.order

        const, ar, variance = self._extract_regime_parameters()
        transition = self.regime_transition[:, :, 0]
        initial_prob = np.asarray(self.model.initial_probabilities, dtype=np.float64)

        # Initialize regime and level histories using the stationary initial distribution
        current_regime = rng.choice(k_regimes, p=initial_prob)
        y_history = [const[current_regime]] * order
        regime_history = [current_regime] * order
        simulated = np.zeros(seq_len, dtype=np.float64)

        for t in range(seq_len):
            # Sample the next regime from the Markov transition matrix
            current_regime = rng.choice(k_regimes, p=transition[:, regime_history[-1]])

            # Draw regime-specific Gaussian innovation
            innovation = rng.normal(loc=0.0, scale=np.sqrt(variance[current_regime]))

            # Switching autoregressive recursion in deviation form
            value = const[current_regime]
            for lag in range(1, order + 1):
                value += ar[current_regime, lag - 1] * (
                    y_history[-lag] - const[regime_history[-lag]]
                )
            value += innovation

            simulated[t] = value
            y_history.append(value)
            regime_history.append(current_regime)

        return simulated
