# -*- coding: utf-8 -*-
"""
Created on 2026/02/18 14:28:15
@author: Whenxuan Wang
@email: wwhenxuan@gmail.com
@url: https://github.com/wwhenxuan/S2Generator
"""

from typing import Optional, Dict, Any

import numpy as np
from scipy import signal
from scipy.linalg import toeplitz
from statsmodels.tsa.stattools import acf

from s2generator.utils._tools import yule_walker
from s2generator.simulator.low_pass_filter import (
    maybe_attach_lowpass,
    maybe_apply_lowpass,
)


class WienerFilterSimulator(object):
    """
    Simulate new time series using a Wiener optimal filter fitted to the input series.

    Any stationary signal can be viewed as the response obtained by exciting a linear system with white noise.

    Inspired by parametric spectral estimation methods, this module constructs a learnable Wiener filter for modeling time series.
    It mainly learns a convolution kernel that transforms a white noise sequence into a sequence with statistical properties similar to the input sequence.Meanwhile,
    it ensures that the autocorrelation and power spectral density of the output exhibit shapes analogous to those of the input sequence.

    Suppose the convolution kernel is a = [1, a1, a2, ..., an], the input white noise sequence is w[n], and the output analog sequence is y[n].
    The filter function is implemented as ::

    y[n] = a[0]*w[n] + a[1]*w[n-1] + ... + a[n]*w[n-n]

    That is, it is generated by exciting a linear system with a white noise sequence.

    We can solve for the filter coefficients a1~an and the noise variance σ² using the Yule-Walker equation.

    This equation is somewhat similar to the spectral estimation of the AR model,
    and its basic principle is as follows::

                             1
         Y(z) = -------------------------------- X(z)
                             -1              -N
                 a[0] + a[1]z  + ... + a[N] z

    From the perspective of modern signal processing, this module is more akin to the parametric spectral estimation method of the AR model than to the Wiener filter.
    In fact, this module can be regarded purely as the first part of the causal Wiener filter,
    namely the whitening process.We only learn the whitening filter and do not learn the de-whitening filter.However,
    in current deep learning-based time series analysis,naming the module as a Wiener filter is more understandable than referring to the spectral estimation theory of the AR model.
    """

    def __init__(
        self,
        filter_order: int = 6,
        revin: Optional[bool] = True,
        random_state: Optional[int] = 42,
        lowpass: bool = False,
        lowpass_kwargs: Optional[Dict[str, Any]] = None,
    ) -> None:
        """
        :param filter_order: The order of the Wiener filter (including a0=1).
        :param revin: Whether to perform reversible normalization (keep the variance of the input sequence unchanged).
        :param random_state: The random seed for reproducibility.
        :param lowpass: Whether to apply low-pass post-processing after ``transform``.
        :param lowpass_kwargs: Optional kwargs forwarded to ``LowPassFilter``.

        :return: None
        """
        # Filter order (including a0=1)
        self.filter_order = filter_order
        self.lag_max = filter_order * 2

        # Record the autocorrelation function value of the input sequence
        self.acf_vals = None

        # Record the autocorrelation matrix R
        # Toeplitz matrix [filter_order x filter_order]
        self.R = None

        # Noise variance σ²
        self._sigma_sq = None

        # Wiener filter coefficients [filter_order, ]
        self._coeffs = None

        # Should we perform normalization
        # (keeping the variance of the input sequence constant)?
        self.revin = revin
        self.mean, self.std = None, None

        # Record the currently used random seed and create a random number generator.
        self.random_state = random_state
        self.rng = np.random.RandomState(seed=random_state)

        # Optional low-pass post-processing of generated series
        self.lowpass = lowpass
        self.lowpass_kwargs = lowpass_kwargs
        self._lowpass_filter = None

        # Record the original time series of input
        self.time_series = None
        # The time series after truncation of the original sequence
        # (removing the first filter_order points to avoid edge effects).
        self.time_series_trimmed = None

        # Record the fitting residuals of the model
        self.residuals = None

        # Record the time series generated by the simulation
        self.simulated_series = None

    def fit(self, time_series: np.ndarray) -> None:
        """
        Fit a Wiener filter and calculate the filter coefficients.

        The specific parameters will be obtained using the Yule-Walker method.

        :param time_series: The input time series to fit the Wiener filter, with shape 1D [seq_len, ] or 2D [num_samples, seq_len].

        :return: None
        """

        # Check the format and length of the input time series.
        time_series = self.check_inputs(time_series)
        # Record the original input sequence
        self.time_series = time_series

        # Should we perform normalization?
        if self.revin:
            self.mean = np.mean(time_series)
            self.std = np.std(time_series)
            time_series = (time_series - self.mean) / self.std

        self.acf_vals = self.acf(time_series=time_series)

        # Constructing the autocorrelation matrix
        self.R = toeplitz(self.acf_vals[: self.filter_order])

        # The filter coefficients and noise variance are obtained by solving the Yule-Walker equation.
        self._coeffs, self._sigma_sq = yule_walker(A=self.R)

        # Initialize noise and calculate the fitted residuals.
        # Note that increasing the filter order is necessary to avoid edge effects.
        white_noise = self.rng.normal(
            0, scale=np.sqrt(self.sigma_sq), size=len(time_series) + self.filter_order
        )
        self.residuals = time_series - self.invoke(white_noise=white_noise)

        # Fit optional low-pass post-filter on the original-scale reference series
        maybe_attach_lowpass(
            self,
            enabled=self.lowpass,
            kwargs=self.lowpass_kwargs,
            reference=self.time_series,
        )

    def transform(
        self, num_samples: int, seq_len: int, random_state: Optional[int] = None
    ) -> np.ndarray:
        """
        Generate new time series by exciting the fitted Wiener filter with white noise.

        :param num_samples: The number of new time series to generate.
        :param seq_len: The length of each generated time series.
        :param random_state: The random seed for reproducibility. If None, it will use the random state of the class instance.

        :return: The generated time series with shape [num_samples, seq_len].
        """

        # Check if the filter coefficients have been calculated; if not, raise an error.
        if self._coeffs is None:
            raise ValueError(
                "The filter coefficients have not been calculated yet; please call the `fit` method first."
            )

        # If a random seed is provided, a new random number generator will be used to generate the random number.
        if random_state is not None:
            rng = np.random.RandomState(seed=random_state)
        else:
            # Otherwise, use the existing random number generator in the class.
            rng = self.rng

        # Generate white noise (zero mean, unit variance) with the same length as the original sequence.
        white_noise = rng.normal(
            0,
            scale=np.sqrt(self.sigma_sq),
            size=(num_samples, seq_len + self.filter_order),
        )  # Note that increasing the filter order is necessary to avoid edge effects.

        # Using white noise to excite the Wiener optimal filter to generate entirely new sequences
        simulated_series = np.zeros(shape=(num_samples, seq_len))

        for i in range(num_samples):
            # Implemented using linear filtering:
            # New sequence = White noise * Wiener filter (convolution)
            simulated_series[i, :] = self.invoke(white_noise=white_noise[i, :])

        # If normalization was performed previously,
        # denormalization is now needed to maintain the same mean and variance as the original sequence.
        if self.revin:
            self.simulated_series = simulated_series * self.std + self.mean
        else:
            self.simulated_series = simulated_series

        self.simulated_series = maybe_apply_lowpass(self, self.simulated_series)
        return self.simulated_series

    def invoke(self, white_noise: np.ndarray) -> np.ndarray:
        """
        Generate directly by calling the filter
        (without generating random noise).

        :param white_noise: The input white noise sequence to excite the filter, with shape 1D [seq_len + filter_order, ].

        :return: The generated time series with shape 1D [seq_len, ].
        """
        if self._coeffs is None:
            raise ValueError(
                "The filter coefficients have not been calculated yet; please call the `fit` method first."
            )

        # Implemented using linear filtering:
        # New sequence = White noise * Wiener filter (convolution)
        simulated_series = signal.lfilter(a=self._coeffs, b=1.0, x=white_noise)

        # Remove edge effects after filtering (first filter_order points)
        return simulated_series[self.filter_order :]

    def acf(
        self,
        time_series: np.ndarray,
        lag_max: Optional[int] = None,
        fft: Optional[bool] = True,
    ) -> np.ndarray:
        """
        Calculate the autocorrelation function (ACF) of the input time series.

        :param time_series: The input time series for which to calculate the ACF, with shape 1D [seq_len, ].
        :param lag_max: The maximum lag for which to calculate the ACF. If None, it defaults to self.lag_max (which is filter_order * 2).
        :param fft: Whether to use FFT to speed up the ACF calculation. Default is True.

        :return: The autocorrelation function values for lags from 0 to lag_max, with shape 1D [lag_max + 1, ].
        """
        return acf(
            time_series, nlags=self.lag_max if lag_max is None else lag_max, fft=fft
        )  # Use FFT to speed up the calculation

    def check_inputs(self, time_series: np.ndarray) -> np.ndarray:
        """
        Check the format and length of the input time series.

        :param time_series: The input time series to check, with shape 1D [seq_len, ] or 2D [num_samples, seq_len].

        :return: The checked and possibly reshaped time series, with shape 1D [seq_len, ].
        """

        # Check if the input is a NumPy array
        if not isinstance(time_series, np.ndarray):
            raise ValueError("The input time series must be a NumPy array.")

        # Check the shape of the input time series. It should be either 1D [seq_len, ] or 2D [num_samples, seq_len].
        if len(time_series.shape) > 2:
            raise ValueError(
                "The input time series must be 1D with [seq_len, ] or 2D with [num_samples, seq_len], but got shape: {}".format(
                    time_series.shape
                )
            )

        if len(time_series.shape) == 2:
            # Flatten a 2D array into a 1D array
            time_series = time_series.flatten()

        if len(time_series) < 2 * self.filter_order:
            raise ValueError(
                f"Input time series length must be at least {2 * self.filter_order} to ensure accurate ACF estimation."
            )

        return time_series

    def set_coeffs(self, coeffs: np.ndarray) -> None:
        """
        Manually set the Wiener filter coefficients (for testing purposes).

        :param coeffs: The Wiener filter coefficients to set, with shape 1D [filter_order, ].

        :return: None
        """
        assert isinstance(coeffs, np.ndarray), "Coefficients must be a NumPy array."
        assert (
            len(coeffs) == self.filter_order
        ), f"Length of coefficients must be equal to filter_order ({self.filter_order})."
        self._coeffs = coeffs

    def set_sigma_sq(self, sigma_sq: float) -> None:
        """
        Manually set the noise variance σ² (for testing purposes).

        :param sigma_sq: The noise variance σ² to set, a positive float.

        :return: None
        """
        # Check if sigma_sq is a numeric value
        assert isinstance(
            sigma_sq, (int, float, np.ndarray)
        ), "Noise variance σ² must be a numeric value."

        # Check if sigma_sq is a positive value
        assert sigma_sq > 0, "Noise variance σ² must be a positive float."

        # If sigma_sq is a NumPy array, check if it is a scalar (shape should be ()).
        if isinstance(sigma_sq, np.ndarray):
            assert sigma_sq.shape == (), "Noise variance σ² must be a scalar value."

        self._sigma_sq = np.asarray(sigma_sq, dtype=np.float64)

    @property
    def coeffs(self) -> np.ndarray:
        """Get the Wiener filter coefficients after fitting the model."""
        if self._coeffs is None:
            raise ValueError(
                "The filter coefficients have not been calculated yet; please call the `fit` method first."
            )
        return self._coeffs

    @property
    def sigma_sq(self) -> float:
        """Get the noise variance σ² after fitting the model."""
        if self._sigma_sq is None:
            raise ValueError(
                "The noise variance has not been calculated yet; please call the `fit` method first."
            )
        return self._sigma_sq
